version: '3.9'
services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      # command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/usr/app
    ports:
      - 8000:8000
