version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "uvicorn http_api:app --reload --reload --host 0.0.0.0"
    volumes:
      - .:/usr/app
    ports:
      - 8000:8000