version: '3.9'
services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: ${ENV:-development}
    volumes:
      - .:/usr/app
    ports:
      - 8000:8000
